# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# This workflow ensures the package passes all checks, including devtools::check()

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, r: "4.3" }
          - { os: macOS-latest, r: "4.3" }
          - { os: windows-latest, r: "4.3" }
    env:
      R_KEEP_PKG_SOURCE: yes
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rcmdcheck

      - name: Run R CMD check
        run: |
          options(repos = c(CRAN = "https://cloud.r-project.org"))
          rcmdcheck::rcmdcheck(error_on = "error", args = "--no-manual", check_dir = "check")
        shell: Rscript {0}

      - name: Upload R CMD check results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: R-CMD-check-results
          path: check
